/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32l432xx.h>

#include "gpio.h"
#include "uart.h"
#include "delay.h"

int main(void)
{
    gpio_init_output(GPIOB, 3);
    uart_init();

    /* Loop forever */
	for(;;)
    {
        gpio_set_hi(GPIOB, 3);
        delay_ms(100);
        gpio_set_lo(GPIOB, 3);
        delay_ms(300);
        uart_puts("enter 1 to switch LED on or 0 to switch LED off\n");
        int c = uart_getc();
        if(c=='1') {
            gpio_set_hi(GPIOB, 3);
            delay_ms(2000);
        }
        else if(c=='0') {
            gpio_set_lo(GPIOB, 3);
            delay_ms(2000);
        }
    }
}
